.PHONY: clean All

All:
	@echo "----------Building project:[ HelloTest - Debug ]----------"
	@cd "HelloTest" && $(MAKE) -f  "HelloTest.mk"
clean:
	@echo "----------Cleaning project:[ HelloTest - Debug ]----------"
	@cd "HelloTest" && $(MAKE) -f  "HelloTest.mk" clean
