.PHONY: clean All

All:
	@echo "----------Building project:[ Lab3 - Debug ]----------"
	@cd "Lab3" && $(MAKE) -f  "Lab3.mk"
clean:
	@echo "----------Cleaning project:[ Lab3 - Debug ]----------"
	@cd "Lab3" && $(MAKE) -f  "Lab3.mk" clean
